### ISSUE TITLE
Feature: eeg-pipes in React Native

### ISSUE THREAD

**Issue by elmines** [neurosity/eeg-pipes#31]
I am utilizing eeg-pipes in conjunction with a React Native Android app. I love eeg-pipes's API, but Babel doesn't run unless I have a debugger window open in the browser:

![screenshot_20181024-193416](https://user-images.githubusercontent.com/22159522/47469022-42dad680-d7c4-11e8-824e-2b775e0cc94f.png)

I presume the transpiler needs a browser window to run? I am quite new to front-end and am more than willing to add this feature myself and do a pull request; I may need a suggestion regarding where to start, however.

**Comment by jdpigeon** [comment]
Hey there! This is exciting stuff. I'm glad to see someone using the pipes on mobile!

This is an issue because the eeg pipes build process only produces code with ES6 syntax. That's been fine for us in the past running node, web, and Electron projects in the past, but maybe we should extend that by compiling all the way to vanilla JS? @alexcastillo 

One workaround that may work for your app is to include @neurosity/pipes in your babel transpilation. Something like this might do it: https://github.com/babel/babel-loader/issues/171

**Comment by alexcastillo** [comment]
Hey @elmines,

Thanks for opening an issue.

What version of React Native are you running? According to the docs, es6 is supported: https://facebook.github.io/react-native/docs/javascript-environment

**Comment by elmines** [comment]
I can now say with near certainty that Babel is not overlooking eeg-pipes; the issue is that it is not transpiling any of the ES6 code inside the eval() statements. I've replicated this error with a tiny module that does something similar:

```js
"use strict";
const messages = ["Wow, I love new ECMAScript syntax tricks", "Don't you?"];
messages.forEach(element => console.log(element));
eval(" const warning = \"Apparently React Native doesn\'t transpile code inside of eval()\"; console.log(warning); ");
```
That `const` declaration in the eval() statement causes the same error shown in the screenshot above. I would assume React Native runs Babel before these eval() statements get a chance to run. I've also attached a (somewhat) pretty-printed version of eeg-pipes.umd.js. The error occurs at the eval() statement on line 36. 

The easiest (but perhaps crudest) solution I can currently think of is an additional distribution with the eval() statements already executed.

[pretty-eeg-pipes.umd.js.zip](https://github.com/neurosity/eeg-pipes/files/2521328/pretty-eeg-pipes.umd.js.zip)

**Comment by jdpigeon** [comment]
Good detective work.

So, those eval statements are how the UMD module system handles importing dependencies. Ideally, in a way that should support both browser and Node (and React Native).

Before we get too deep in troubleshooting our build configuration or generating another distribution, can you check that this issue isn't because you're on an old version of node? https://stackoverflow.com/questions/36789889/syntaxerror-use-of-const-in-strict-mode

const and let should be able to be used in strict mode in the newest version of node, I believe

**Comment by elmines** [comment]
I actually did consider that and upgraded to Node 11.0.0. I'm currently looking into a Babel plugin that also transforms code inside eval() statements: https://babeljs.io/docs/en/babel-plugin-transform-eval

**Comment by jdpigeon** [comment]
Hmmm ok. Don't worry about that babel plugin, the problem is on our side with our umd config then.

Until we fix it, try pointing your app to our other bundles instead. You can do that by changing eeg pipes package.json "main" value to ""dist/eeg-pipes.var.js" or ""dist/electron.js"

**Comment by elmines** [comment]
I actually did try out the other bundles and encountered the same issue. By all means let me know if there is any way I can help; I don't want to make a feature request without being willing to pitch in.

**Comment by elmines** [comment]
Since React Native has its own Babel transformations, its sufficient to just produce a distribution in ES6, as long as it has no code in eval() statements.

My changes can be summarized as follows:
- Add an extra dist to the webpack.config.js (index.react.js)
- Upgrade webpack-cli to 3.1.2 (I could not get the build scripts to run correctly otherwise)

That said, it is apparently difficult to install the [exact packages in the yarn.lock](https://yarnpkg.com/blog/2017/05/31/determinism/) file; so I fear that the slight version changes to the installed packages (in addition to my changing the webpack-cli dependency) could break the code on other machines.

I have a commit at https://github.com/elmines/eeg-pipes/commit/793277861d0738a9ba5df0da1a3eb0d5be8db580. I'm happy to make whatever modifications are necessary before a pull request.
